- hosts: MYDEMO
  gather_facts: no
  tasks:
  - win_domain_membership:
      dns_domain_name: fd.local
      hostname: MYDEMO
      domain_admin_user: adminj
      domain_admin_password: password123!
      domain_ou_path: "OU=Windows,OU=Servers,DC=ansible,DC=vagrant"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required

