- name: current time
  local_action: shell date +%D
  register: current_time

#- debug: current_time

#- debug: current_time.stdout

- name: Check for proper machine name 
  fail: msg="machineName is not defined"
  when: machineName is not defined

- name: Check for a provided template name
  fail: msg="please provide a template name"
  when: vmtemplate is not defined

- name: Check for vSphere access parameters
  fail: msg="Must set vsphere_login and vsphere_password in a Vault"
  when: (vsphere_login is not defined) or (vsphere_password is not defined)

- name: debug vCenter hostname
  debug: msg="vcenter_hostname = '{{ vcenter_hostname }}'"

- name: Create VM from template - DC1
  when: vcenter_hostname == "vcsa1.fd.local"
  vmware_guest:
    name: "{{ machineName }}"
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vsphere_login }}'
    password: '{{ vsphere_password }}'
    validate_certs: no
    esxi_hostname: '{{ esx_hostname }}'
    state: poweredon
    datacenter: "{{ vcenter_datacenter }}"
    template: "{{ vmtemplate }}"
    hardware:
      memory_mb: "{{ vm_memory | default(1024) }}"
      num_cpus: 2
    wait_for_ip_address: yes

- name: get facts from vm
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username:  "{{ vsphere_login }}"
    datacenter: "{{ vcenter_datacenter }}"
    password:  "{{ vsphere_password }}"
    folder: "{{ vcenter_datacenter }}/vm/"
    name: "{{ machineName }}"
    validate_certs: no
  register: newMachine

- name:  Add guest to hosts
  add_host: 
    hostname: "{{ machineName }}"
    ansible_host: "{{ newMachine.instance.ipv4 }}"

- name: time to go to time
  setup: filter=ansible_local
