  - name: Check for proper machine name
    fail: msg="machineName is not defined"
    when: machineName is not defined

  - name: rename machine using powershell
    script: ../files/machineServername.ps1 "{{ machineName }}"

  - win_updates:
      category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups

  - name: debug var ansible_ssh_host
    debug: msg="var 'ansible_ssh_host' = '{{ ansible_ssh_host }}'"

  - name: reboot machine only
    raw: shutdown /r /t 0
