  - win_domain_membership:
      dns_domain_name: fd.local
      hostname: "{{ machineName }}"
      domain_admin_user: administrator@fd.local
      domain_admin_password: Sneakypies33
      domain_ou_path: "OU=Servers,DC=fd,DC=local"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required
